version: "3.3"

services:

############## NGINX ##############

  web:
    container_name: nginx
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    restart: always

############ WORDPRESS ############

  wordpress:
    build:
      context: ./WordPress
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    restart: always

############# MARIADB #############

  mariadb:
    build:
      context: ./MariaDB
      dockerfile: Dockerfile
      args:
        DB_NAME: $(DB_NAME)
        DB_USER: $(DB_USER)
        DB_USER_PSWD: $(DB_USER_PASSWORD)
        DB_ROOT_PSWD: $(DB_ROOT_PASSWORD)
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

############# NETWORK #############

networks:
  inception:
    driver: bridge
    name: inception

############# VOLUMES #############

volumes:
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device : /home/max/wordpress
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device : /home/max/mariadb